bash: minor fixes to scripts
    Make paths in .bash_profile absolute, else ssh logins not starting
    in the user's home directory will not be able to find .bashrc and
    .profile.

    The scripts leo, leoi and printcolors still had local variable
    declarations from when they were implemented as functions.
    Since all script variables are local unless exported and the local
    command is not really available outside of functions, this is now
    removed.

    Most of these scripts do not require any commands not provided by
    the GNU coreutils (a notable exception being which), for scripts
    requiring non-standard software (here leo and leoi) check if their
    dependencies are available on the PATH before execution.

diff --git a/bash/.bash/bin/leo b/bash/.bash/bin/leo
--- a/bash/.bash/bin/leo
+++ b/bash/.bash/bin/leo
@@ -3,5 +3,13 @@
 # leo - LeoDictionary
 # requires: w3m
 # usage:    leo <searched-word(german or english)>
-local phrase='\(Substantive\|Verben\|Adjektive\|Beispiele\|Phrasen\|Ähnliche\|Suchumfeld\|Diskussionen\)'
+
+# check if w3m is available
+if !( which w3m >/dev/null 2>&1 ); then
+  echo "This script requires w3m to be available on the PATH" >&2
+  echo "Aborting..." >&2
+  exit 1
+fi
+
+phrase='\(Substantive\|Verben\|Adjektive\|Beispiele\|Phrasen\|Ähnliche\|Suchumfeld\|Diskussionen\)'
 w3m -dump "http://pda.leo.org/?search=\"$*\"" | sed -n "/\(${phrase}::\)\+/I,\$p" | less
